name: Mantener activo
on:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:
jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
